# render.yaml

services:
  - type: web
    name: nestjs
    env: docker
    rootDir: ./backend
    dockerfilePath: Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: POSTGRES_HOST
        value: postgres
      - key: POSTGRES_PORT
        value: 5432
      - key: RABBITMQ_HOST
        value: rabbitmq
      - key: RABBITMQ_PORT
        value: 5672
      - key: DATABASE_URL
        value: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/chatapp?schema=public
      - key: PORT
        value: 3333
      - key: FRONTEND_URL
        value: ${frontend.url}
      - key: FRONTEND_DOMAIN
        value: ${frontend.hostname}
      - key: RABBITMQ_URL
        value: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - key: JWT_ACCESS_TOKEN_SECRET
        sync: false
      - key: JWT_REFRESH_TOKEN_SECRET
        sync: false
      - key: CSRF_SECRET
        sync: false
      - key: CSRF_COOKIE_NAME
        value: "__Host-dx.x-csrf-token"
      - key: TOKEN_COOKIE_MODE
        value: false
      - key: NODE_ENV
        value: development
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: password
      - key: RABBITMQ_USER
        value: admin
      - key: RABBITMQ_PASSWORD
        value: password

  - type: pserv
    name: postgres
    env: docker
    rootDir: ./servers/postgres-server
    dockerfilePath: Dockerfile
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: password
      - key: POSTGRES_DB
        value: chatapp


  - type: pserv
    name: rabbitmq
    env: docker
    rootDir: ./servers/rabbitmq-server
    dockerfilePath: Dockerfile
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: admin
      - key: RABBITMQ_DEFAULT_PASS
        value: password


  - type: pserv
    name: redis
    env: docker
    rootDir: ./servers/redis-server
    dockerfilePath: Dockerfile


  - type: web
    name: frontend
    env: docker
    rootDir: ./frontend
    dockerfilePath: Dockerfile
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_API_BASE_URL
        value: /api/v1
      - key: VITE_GRAPHQL_HTTP_URL
        value: /graphql
